# Generated by Django 2.2.3 on 2020-09-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0002_auto_20200912_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desciption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
