# Generated by Django 2.2.3 on 2020-09-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0006_ratingevaluationstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sender_name',
        ),
    ]
