# Generated by Django 2.2.3 on 2020-09-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0007_remove_review_sender_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingEvaluationString',
        ),
    ]
