# Generated by Django 2.2.3 on 2020-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0008_delete_ratingevaluationstring'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingEvaluationString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_review', models.CharField(max_length=255)),
                ('event', models.CharField(default='review added', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
