# Generated by Django 2.2.3 on 2020-09-13 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0009_ratingevaluationstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingevaluationstring',
            name='fromat_string_review',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratingevaluationstring',
            name='event',
            field=models.CharField(default='review string added', max_length=255),
        ),
    ]
