# Generated by Django 2.2.3 on 2020-09-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0010_auto_20200913_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingEvaluationString',
        ),
    ]
