# Generated by Django 2.2.3 on 2020-09-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0011_delete_ratingevaluationstring'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingEvaluationString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_review', models.CharField(max_length=255)),
                ('fromat_string_review', models.CharField(max_length=255)),
                ('event', models.CharField(default='review string added', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_product_string', to='reviewapp.Product')),
            ],
        ),
    ]
